second commit
LethaboMot/Portfolio pull request #1
Opened 2022-10-28 15:37 UTC by LethaboMot

2022-10-28 18:19 UTC, vickymarz requested changes
Hi @LethaboMot, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

You have submitted a project, that has failed a linter check. Kindly fix your linter errors and submit again 👍🏽  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-29 00:07 UTC, Olamarx requested changes
Hi @LethaboMot, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

## Highlights
- Linters passed ✔️ 
- Meaningful commit messages ✔️ 
- Good use of Git and Github flows ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 00:07 UTC, Olamarx commented on index.html
> +                <img src="images/Primary Text2.svg" alt="text" align="center">
- [ ] This image should be used in the styling. If an image is not part of the content (for aesthetic reasons) it should be used as a CSS background image.

2022-10-29 00:07 UTC, Olamarx commented on index.html
> +                <img src="images/connect.svg" alt="text" align="center">
- [ ] This image should be used in the styling. If an image is not part of the content (for aesthetic reasons) it should be used as a CSS background image.

2022-10-29 00:07 UTC, Olamarx commented on index.html
> +                <img src="images/Hamburger button.svg">
- [ ] This image should be used in the styling. If an image is not part of the content (for aesthetic reasons) it should be used as a CSS background image.

2022-10-29 00:07 UTC, Olamarx commented on index.html
> +            </div>
- [ ] Kindly replace the div with ul tag and wrap the a tags in li tag. This is for semantic reasons.

2022-10-29 11:45 UTC, PinkMoon25 approved these changes
Hi @LethaboMot , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/XreQmk7ETCak0/giphy.gif"/>

## Highlights
Linters passed :heavy_check_mark: 
Meaningful commit messages  :heavy_check_mark: 
Good use of Git and Github flows  :heavy_check_mark: 
used flexbox for the layout  :heavy_check_mark: 
follows figma design  :heavy_check_mark: 

## Optional suggestions
#### _**You have done a good job implementing the changes, I have added some Optional changes please take them into consideration in order to Improve our site and make it more similar to the figma template**_
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 11:45 UTC, PinkMoon25 commented on style.css
> +}
[OPTIONAL] Currently your header section does not have any padding-top, and is sticking to the top like this :point_down: 
![image](https://user-images.githubusercontent.com/97521557/198829162-c88060e4-a4cd-4a92-8af5-2b2cafa1c5e8.png)
how it is supposed to be :point_down: 
![image](https://user-images.githubusercontent.com/97521557/198829207-f1b3532e-355e-44d5-9492-43ec1ddfc0a4.png)
you can fix this by setting the padding on your header like this :point_down: 
```
header {
  padding: 24px;
}
```

2022-10-29 11:45 UTC, PinkMoon25 commented on style.css
> +}
[OPTIONAL] Currently your intro section does not have any padding-left and padding-right and is sticking at both side like this :point_down: 
![image](https://user-images.githubusercontent.com/97521557/198829323-d4172f00-f017-4f88-aaf1-b48d8896a8d7.png)
It should be like this :point_down: 
![image](https://user-images.githubusercontent.com/97521557/198829342-ffa6e56d-07fa-44a7-a683-1724adaab937.png)
You can fix this by removing `width:100% `and adding a `padding: 0 22px; `

2022-10-29 14:48 UTC, cynthiainga reviewed
Hi @LethaboMot, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that not corresponding to the activity. You submit the project the activity name is `Portfolio: finish mobile version` and I think you should submit `Portfolio: setup and mobile first` 🙃

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-29 15:58 UTC, Favourezeugwa reviewed
Hi @LethaboMot , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌  ❌ 

You have submitted the wrong project. This pull request contains your `portfolio set-up` branch  and not the `finish mobile version`.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-29 19:55 UTC, merged